#!/usr/bin/tclsh

set prompt "# "


puts "START"
puts "give your command"


proc parse_line {line} {
	set parcmd [dict create]

	if {[string length $line] == 0} {
		dict set parcmd cmd "none"
		return $parcmd
	}
	set param_list [split $line]
	set cmd [lindex $param_list 0]
	set args [lrange $param_list 1 end]
	dict set parcmd cmd $cmd
	dict set parcmd args $args
	return $parcmd
}


while {1} {
	puts -nonewline $prompt
	flush stdout
	gets stdin line
	set parcmd [parse_line [string trimright [string tolower $line] " \r\n"]]

	switch [dict get $parcmd cmd] {
		"none" {
			puts "NONE:"
		}
		"quit" {
			puts "END"
			exit 0
		}
		"get" {
			puts "GET: [dict get $parcmd args]"
		}
		"put" {
			puts "PUT: [dict get $parcmd args]"
		}
	}

}

