#!/usr/bin/tclsh

set prompt "# "

proc start_cli {prompt} {
	puts "START"
	puts "give your command"
	puts -nonewline $prompt
	flush stdout
}

proc parse_line {line} {
	set parcmd [dict create]

	if {[string length $line] == 0} {
		dict set parcmd cmd "none"
		return $parcmd
	}
	set param_list [split $line]
	set cmd [lindex $param_list 0]
	set args [lrange $param_list 1 end]
	dict set parcmd cmd $cmd
	dict set parcmd args $args
	return $parcmd
}

proc read_line {prompt} {
	gets stdin line
	set parcmd [parse_line [string trimright [string tolower $line] " \r\n"]]

	switch [dict get $parcmd cmd] {
		"none" {
			puts "NONE:"
		}
		"quit" {
			puts "END"
			exit 0
		}
		"get" {
			puts "GET: [dict get $parcmd args]"
		}
		"put" {
			puts "PUT: [dict get $parcmd args]"
		}
	}
	;# print prompt
	puts -nonewline $prompt
	flush stdout
}



;# main
start_cli $prompt

fileevent stdin readable [list read_line $prompt]


vwait forever

