#!/usr/bin/tclsh

package require Tclx



proc sigint_handler {sock} {
	puts "Bye ..."
	puts $sock "Bye..."
	exit 0

}




set ns [socket 127.0.0.1 7707]
fconfigure $ns -buffering line

signal trap SIGINT [list sigint_handler $ns]

puts $ns "test 1"

while {1} {

	if {[eof $ns] || [catch {gets $ns line}]} {
		puts "error"
		break
	} else {
		puts "$line"
	}

}

after 500

close $ns


