#!/bin/sh -a

#\
exec expect "$0" "$@"
package require tdom


proc read_data {chan} {
	puts "call read"
	
	if {[eof $chan] == 1} {
		puts "DONE"
		close $chan
	} else {
		set data [read $chan]
		puts $chan "OK"
		flush $chan
		if { $data == "\n"} {
			puts "enter"
		}
		puts "$data"
	}

}


proc accept {chan addr port} {
	fconfigure $chan -blocking 0
	fileevent $chan readable [list read_data $chan] 
}                                       

socket -server accept 12345             
vwait forever                           


